import Head from "next/head";
import Link from "next/link";

export default function Home() {
  return (
    <>
      <Head>
        <title>NOVA E-Commerce DEMO</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div>
          <div>
            <Link href="/api/auth/login">Login</Link>
          </div>
          <div>
            <Link href="/api/auth/logout">Logout</Link>
          </div>
          <div>
            <Link href="/account">Mein Account</Link>
          </div>
        </div>
      </main>
    </>
  );
}
